version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

build:
  jobs:
    pre_build:
      - npm install
      - npm run docs 